build:
  maxIssues: -1

config:
  validation: true
  warningsAsErrors: false

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
  #  - 'FindingsReport'
    - 'FileBasedFindingsReport'
    - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
    - 'HtmlOutputReport'
  #  - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'SarifOutputReport'
    - 'MdOutputReport'

complexity:
  TooManyFunctions:
    thresholdInClasses: 12
    excludes:
      - '**/Vector3.kt'

performance:
  SpreadOperator:
    active: false

potential-bugs:
  ImplicitDefaultLocale:
    active: false

style:
  excludes: ['**/Test.kt']
  WildcardImport:
    active: false
  MagicNumber:
    active: false